# masterbikes-app/backend/Dockerfile
FROM node:18-alpine

WORKDIR /app

# Este comando mantiene el contenedor corriendo sin hacer nada.
# Más adelante lo reemplazaremos con nuestro servidor de API.
CMD tail -f /dev/null